---
- apt_repository:
    repo: "{{ apache_ondrej_repository }}"

- name: Ensure apache is stopped (if already installed)
  service: name=apache2 state=stopped
  when: _apache_version.stdout != ""

- name: Install / Update "apache2" package
  apt:
    name: apache2
    state: latest
    update_cache: yes
  when: apache_ondrej_install

- name: Ensure apache is started
  service: name=apache2 state=started
  when: apache_ondrej_install
